images_loc: ../data
labels_loc: ../data
config_loc: ../data/dataset.yaml
test_command: "python ../train.py --weights yolov5s.pt --batch 2 --epochs 1 --data unittest_dataset.yaml --project runs/train"
run_dir: runs/train/exp
model_loc: ./yolov5s.pt
ref_precision: 0.0014749
ref_recall: 0.5
ref_map_0.5: 0.0078968
ref_map_0.5_0.95: 0.0031587