images_loc: ../gse-data-preparation/images
labels_loc: ../gse-data-preparation/labels
config_loc: ../gse-data-preparation/dataset.yaml
move_dest: ./
config_loc_new: ./dataset.yaml
project_name: /runs/train